import type { Metadata } from "next";
import localFont from "next/font/local";
import { Pacifico, Inter, Fira_Sans_Condensed } from "next/font/google";
import "./globals.css";
import { APP_NAME } from "@/configs";
import { Toaster } from "react-hot-toast";
import TanStackQueryProvider from "@/providers/TanStackQueryProvider";
import Image from "next/image";
import Footer from "@/components/footer/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: APP_NAME,
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};
const pacifico = Pacifico({
  variable: "--font-pacifico",
  weight: "400",
  subsets: ["latin"],
});
const inter = Inter({
  variable: "--font-inter",
  weight: ["400", "700", "900"],
  subsets: ["latin"],
});
const firaSansCondensed = Fira_Sans_Condensed({
  variable: "--font-fira-sans-condensed",
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TanStackQueryProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${pacifico.variable} ${inter.variable} ${firaSansCondensed.variable} antialiased  bg-[#2d3335] max-w-[500px] mx-auto`}
        >
          <Toaster
            position="top-center"
            toastOptions={{
              duration: 4000,
              style: {
                fontSize: ".85em",
              },
            }}
          />

          <div className="h-dvh relative bg-brandBeige">
            <div className="absolute inset-0 overflow-y-auto flex flex-col">
              <div className="flex-1 pb-20">
                <div className="text-center py-10">
                  <h1 className="pacifico text-7xl text-brandDarkBrown">
                    Welcome to Tablecheck
                  </h1>
                </div>
                <div className="flex w-full justify-center items-center px-10">
                  {children}
                </div>
              </div>
            </div>
            <Footer />
          </div>
        </body>
      </html>
    </TanStackQueryProvider>
  );
}
