import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { APP_NAME } from "@/configs";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: APP_NAME,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  bg-[#2d3335] max-w-[500px] mx-auto`}
      >
        <div className="h-dvh relative bg-brandBeige">
          <div className="absolute inset-0 overflow-y-auto flex flex-col">
            <div className="flex-1">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
